// Generated by gencpp from file lab3/Pathsrv.msg
// DO NOT EDIT!


#ifndef LAB3_MESSAGE_PATHSRV_H
#define LAB3_MESSAGE_PATHSRV_H

#include <ros/service_traits.h>


#include <lab3/PathsrvRequest.h>
#include <lab3/PathsrvResponse.h>


namespace lab3
{

struct Pathsrv
{

typedef PathsrvRequest Request;
typedef PathsrvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Pathsrv
} // namespace lab3


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::lab3::Pathsrv > {
  static const char* value()
  {
    return "f1fa7bf596f4be272e361a20bf7c865c";
  }

  static const char* value(const ::lab3::Pathsrv&) { return value(); }
};

template<>
struct DataType< ::lab3::Pathsrv > {
  static const char* value()
  {
    return "lab3/Pathsrv";
  }

  static const char* value(const ::lab3::Pathsrv&) { return value(); }
};


// service_traits::MD5Sum< ::lab3::PathsrvRequest> should match 
// service_traits::MD5Sum< ::lab3::Pathsrv > 
template<>
struct MD5Sum< ::lab3::PathsrvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::lab3::Pathsrv >::value();
  }
  static const char* value(const ::lab3::PathsrvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::lab3::PathsrvRequest> should match 
// service_traits::DataType< ::lab3::Pathsrv > 
template<>
struct DataType< ::lab3::PathsrvRequest>
{
  static const char* value()
  {
    return DataType< ::lab3::Pathsrv >::value();
  }
  static const char* value(const ::lab3::PathsrvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::lab3::PathsrvResponse> should match 
// service_traits::MD5Sum< ::lab3::Pathsrv > 
template<>
struct MD5Sum< ::lab3::PathsrvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::lab3::Pathsrv >::value();
  }
  static const char* value(const ::lab3::PathsrvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::lab3::PathsrvResponse> should match 
// service_traits::DataType< ::lab3::Pathsrv > 
template<>
struct DataType< ::lab3::PathsrvResponse>
{
  static const char* value()
  {
    return DataType< ::lab3::Pathsrv >::value();
  }
  static const char* value(const ::lab3::PathsrvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // LAB3_MESSAGE_PATHSRV_H
