// Generated by gencpp from file lab32/Pathsrv.msg
// DO NOT EDIT!


#ifndef LAB32_MESSAGE_PATHSRV_H
#define LAB32_MESSAGE_PATHSRV_H

#include <ros/service_traits.h>


#include <lab32/PathsrvRequest.h>
#include <lab32/PathsrvResponse.h>


namespace lab32
{

struct Pathsrv
{

typedef PathsrvRequest Request;
typedef PathsrvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Pathsrv
} // namespace lab32


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::lab32::Pathsrv > {
  static const char* value()
  {
    return "f1fa7bf596f4be272e361a20bf7c865c";
  }

  static const char* value(const ::lab32::Pathsrv&) { return value(); }
};

template<>
struct DataType< ::lab32::Pathsrv > {
  static const char* value()
  {
    return "lab32/Pathsrv";
  }

  static const char* value(const ::lab32::Pathsrv&) { return value(); }
};


// service_traits::MD5Sum< ::lab32::PathsrvRequest> should match 
// service_traits::MD5Sum< ::lab32::Pathsrv > 
template<>
struct MD5Sum< ::lab32::PathsrvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::lab32::Pathsrv >::value();
  }
  static const char* value(const ::lab32::PathsrvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::lab32::PathsrvRequest> should match 
// service_traits::DataType< ::lab32::Pathsrv > 
template<>
struct DataType< ::lab32::PathsrvRequest>
{
  static const char* value()
  {
    return DataType< ::lab32::Pathsrv >::value();
  }
  static const char* value(const ::lab32::PathsrvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::lab32::PathsrvResponse> should match 
// service_traits::MD5Sum< ::lab32::Pathsrv > 
template<>
struct MD5Sum< ::lab32::PathsrvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::lab32::Pathsrv >::value();
  }
  static const char* value(const ::lab32::PathsrvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::lab32::PathsrvResponse> should match 
// service_traits::DataType< ::lab32::Pathsrv > 
template<>
struct DataType< ::lab32::PathsrvResponse>
{
  static const char* value()
  {
    return DataType< ::lab32::Pathsrv >::value();
  }
  static const char* value(const ::lab32::PathsrvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // LAB32_MESSAGE_PATHSRV_H
